# -*- coding: utf-8 -*-

CATEGORIES = (
  (1, 'Arte y Humanidades'),
  (2, 'Casa y Jardín'),
  (3, 'Deportes'),
  (4, 'Familia y Relaciones'),
  (5, 'Juegos y Recreación'),
  (6, 'Música y Entretenimiento'),
  (7, 'Noticias y Actualidad'),
  (8, 'Sociedad y Cultura'),
  (9, 'Autos y Medios de Transporte'),
  (10, 'Ciencia'),
  (11, 'Educación'),
  (12, 'Gastronomía'),
  (13, 'Mascotas'),
  (14, 'Negocios'),
  (15, 'Política y Gobierno'),
  (16, 'Restaurantes'),
  (17, 'Turismo'),
  (18, 'Belleza y Estilo'),
  (19, 'Ciencias Sociales'),
  (20, 'Embarazo y Maternidad'),
  (21, 'Internet y Computación'),
  (22, 'Medio Ambiente'),
  (23, 'Negocios y Finanzas'),
  (24, 'Electrónica'),
  (25, 'Salud y Belleza'),
)
